import {
  CodeSearchResult,
  GraphNode,
  GraphEdge,
  DebugAnalysisResult,
  PRReviewDetail,
  SecurityFindingDetail,
} from "@/types/developer-intelligence";

export const MOCK_SEARCH_RESULTS: CodeSearchResult[] = [
  {
    id: "sr-1",
    repository: "ecommerce-platform",
    branch: "main",
    file: "src/auth/middleware.py",
    language: "Python",
    functionName: "authenticate()",
    codeSnippet: `def authenticate(request):\n    token = extract_token(request)\n    user = validate_token(token)\n    request.state.user = user\n    return user`,
    relevance: 96,
    denseScore: 0.94,
    bm25Score: 0.88,
    hybridScore: 0.92,
    startLine: 42,
    endLine: 67,
    retrievalMethod: "Dense + BM25",
  },
  {
    id: "sr-2",
    repository: "payment-service",
    branch: "main",
    file: "src/auth/hmac.py",
    language: "Python",
    functionName: "verify_webhook_signature()",
    codeSnippet: `def verify_webhook_signature(payload: bytes, signature: str, secret: str) -> bool:\n    computed = hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()\n    return hmac.compare_digest(f"sha256={computed}", signature)`,
    relevance: 93,
    denseScore: 0.91,
    bm25Score: 0.86,
    hybridScore: 0.89,
    startLine: 18,
    endLine: 36,
    retrievalMethod: "Dense + BM25",
  },
  {
    id: "sr-3",
    repository: "auth-gateway",
    branch: "main",
    file: "pkg/jwt/verifier.go",
    language: "Go",
    functionName: "VerifyHMAC()",
    codeSnippet: `func VerifyHMAC(tokenString string, key []byte) (*Claims, error) {\n    token, err := jwt.ParseWithClaims(tokenString, &Claims{}, func(t *jwt.Token) (interface{}, error) {\n        return key, nil\n    })\n    return token.Claims.(*Claims), err\n}`,
    relevance: 88,
    denseScore: 0.89,
    bm25Score: 0.82,
    hybridScore: 0.86,
    startLine: 52,
    endLine: 74,
    retrievalMethod: "Dense",
  },
  {
    id: "sr-4",
    repository: "campus-help-chatbot",
    branch: "master",
    file: "src/services/session.ts",
    language: "TypeScript",
    functionName: "createStudentSession()",
    codeSnippet: `export async function createStudentSession(studentId: string, token: string) {\n  const decoded = await verifyToken(token);\n  return await redis.set(\`session:\${studentId}\`, JSON.stringify(decoded), { ex: 3600 });\n}`,
    relevance: 84,
    denseScore: 0.82,
    bm25Score: 0.79,
    hybridScore: 0.81,
    startLine: 28,
    endLine: 45,
    retrievalMethod: "BM25",
  },
];

export const MOCK_GRAPH_NODES: GraphNode[] = [
  {
    id: "node-ecom",
    name: "ecommerce-platform",
    type: "repository",
    repository: "ecommerce-platform",
    description: "Primary Next.js storefront & GraphQL API Gateway",
    dependencies: ["node-pay", "node-auth", "node-db"],
    dependents: ["node-mobile"],
    metrics: { loc: 14820, chunkCount: 24821 },
  },
  {
    id: "node-pay",
    name: "payment-service",
    type: "repository",
    repository: "payment-service",
    description: "Stripe & PayPal payment processing service with webhook HMAC validation",
    dependencies: ["node-db", "node-auth"],
    dependents: ["node-ecom"],
    metrics: { loc: 5890, chunkCount: 8910 },
  },
  {
    id: "node-auth",
    name: "auth-gateway",
    type: "repository",
    repository: "auth-gateway",
    description: "Centralized OAuth2 / RS256 JWT Token Issuer and SSO Gateway",
    dependencies: ["node-db"],
    dependents: ["node-ecom", "node-pay", "node-campus"],
    metrics: { loc: 3200, chunkCount: 5410 },
  },
  {
    id: "node-campus",
    name: "campus-help-chatbot",
    type: "repository",
    repository: "campus-help-chatbot",
    description: "Student portal virtual assistant with vector-based knowledge retrieval",
    dependencies: ["node-auth", "node-db"],
    dependents: [],
    metrics: { loc: 2800, chunkCount: 4120 },
  },
  {
    id: "node-db",
    name: "PostgreSQL (pgvector)",
    type: "module",
    repository: "database-cluster",
    description: "Shared PostgreSQL 16 instance with 1024D vector embeddings and ACID transactions",
    dependencies: [],
    dependents: ["node-ecom", "node-pay", "node-auth", "node-campus"],
    metrics: { loc: 0, chunkCount: 82491 },
  },
  {
    id: "node-mobile",
    name: "mobile-app",
    type: "repository",
    repository: "mobile-app",
    description: "React Native mobile client for iOS and Android",
    dependencies: ["node-ecom", "node-auth"],
    dependents: [],
    metrics: { loc: 8400, chunkCount: 14200 },
  },
];

export const MOCK_GRAPH_EDGES: GraphEdge[] = [
  { id: "e1", source: "node-ecom", target: "node-pay", label: "POST /v1/charge", type: "api" },
  { id: "e2", source: "node-ecom", target: "node-auth", label: "JWT Verify", type: "api" },
  { id: "e3", source: "node-pay", target: "node-auth", label: "OAuth Introspection", type: "api" },
  { id: "e4", source: "node-ecom", target: "node-db", label: "pgvector query", type: "depends_on" },
  { id: "e5", source: "node-pay", target: "node-db", label: "Ledger transactions", type: "depends_on" },
  { id: "e6", source: "node-mobile", target: "node-ecom", label: "GraphQL query", type: "api" },
  { id: "e7", source: "node-campus", target: "node-auth", label: "SSO Bearer", type: "api" },
];

export const MOCK_DEBUG_ANALYSES: DebugAnalysisResult[] = [
  {
    id: "dbg-1",
    query: "TypeError: Cannot read properties of undefined (reading 'amount') at processPayment in src/services/payment.ts:142",
    timestamp: "Just now",
    rootCause: "A nullable payment object is being passed to processPayment() without parameter validation or early return guard.",
    likelySourceFile: "src/services/payment.ts",
    likelySourceRepo: "payment-service",
    likelyFunction: "processPayment()",
    startLine: 140,
    endLine: 155,
    confidence: 94,
    severity: "High",
    impact: "Causes 500 Internal Server Error when checkout requests contain empty line item structures.",
    suggestedFixDiff: `  export async function processPayment(payment: PaymentIntent) {
+   if (!payment || !payment.amount) {
+     throw new PaymentError("Payment intent or amount data missing");
+   }
    return await stripe.charges.create({ amount: payment.amount });
  }`,
    relatedFiles: [
      {
        file: "src/services/payment.ts",
        repo: "payment-service",
        relationship: "Origin of TypeError throw",
        relevance: 98,
        lineRange: "140-155",
      },
      {
        file: "src/api/checkout.ts",
        repo: "ecommerce-platform",
        relationship: "Caller constructing payload without validation",
        relevance: 91,
        lineRange: "84-110",
      },
      {
        file: "src/models/intent.ts",
        repo: "payment-service",
        relationship: "Type definition showing nullable amount",
        relevance: 86,
        lineRange: "12-25",
      },
    ],
  },
];

export const MOCK_PR_DETAILS: PRReviewDetail[] = [
  {
    id: "pr-128",
    number: 128,
    title: "Refactor authentication middleware and JWT header extraction",
    repository: "ecommerce-platform",
    author: "sarah-dev",
    sourceBranch: "feat/auth-refactor",
    targetBranch: "main",
    changedFiles: 12,
    additions: 340,
    deletions: 110,
    overallRisk: "Medium",
    score: 72,
    aiReviewStatus: "Available",
    affectedModules: 4,
    affectedRepositories: 2,
    dependencyImpactChain: [
      "ecommerce-platform/middleware",
      "ecommerce-platform/graphql-gateway",
      "payment-service/webhook-validator",
    ],
    findings: [
      {
        id: "f-1",
        title: "Authentication middleware may bypass validation when the token is missing",
        severity: "High",
        file: "src/auth/middleware.py",
        repo: "ecommerce-platform",
        startLine: 42,
        endLine: 57,
        explanation: "The exception handler catches all jwt.PyJWTError exceptions but returns None instead of raising an HTTP 401 response.",
        whyItMatters: "Requests may reach downstream protected route handlers without an authenticated user identity object.",
        codeSnippet: `42  try:\n43      payload = jwt.decode(token, SECRET, algorithms=['HS256'])\n44  except jwt.PyJWTError:\n45      pass  # <--- Vulnerability: should raise HTTPException(401)`,
        suggestedFix: "Raise HTTPException(status_code=401, detail='Invalid or missing authentication credentials')",
      },
      {
        id: "f-2",
        title: "Unpinned dependency version for crypto-js",
        severity: "Medium",
        file: "package.json",
        repo: "ecommerce-platform",
        startLine: 18,
        endLine: 24,
        explanation: "Version constraint specifies ^4.1.1 which can introduce breaking changes on automated CI builds.",
        whyItMatters: "Build repeatability can drift across deployment containers.",
        codeSnippet: `18  "crypto-js": "^4.1.1"`,
        suggestedFix: 'Pin to exact patch version "crypto-js": "4.2.0"',
      },
    ],
  },
];

export const MOCK_SECURITY_FINDINGS: SecurityFindingDetail[] = [
  {
    id: "sec-101",
    title: "Potential hardcoded API credential in config module",
    severity: "High",
    category: "Secrets",
    repository: "payment-service",
    file: "src/config.py",
    line: 18,
    status: "Open",
    detectedAt: "2 hours ago",
    description: "A sensitive Stripe test secret key was committed directly into the source file.",
    evidenceSnippet: `18  STRIPE_API_KEY = "sk_test_51MzXXXXXXXXXXXXXXXXXXXXXXXX"`,
    recommendedAction: "Move the credential to environment variables (e.g. process.env.STRIPE_SECRET_KEY) and rotate the exposed API key in the Stripe developer portal.",
  },
  {
    id: "sec-102",
    title: "JWT signature fallback with default insecure secret",
    severity: "Critical",
    category: "Authentication",
    repository: "auth-gateway",
    file: "pkg/jwt/signer.go",
    line: 42,
    status: "Open",
    detectedAt: "4 hours ago",
    description: "If JWT_SECRET environment variable is unset, the system defaults to a hardcoded fallback string.",
    evidenceSnippet: `42  secret := os.Getenv("JWT_SECRET")\n43  if secret == "" { secret = "default-insecure-secret" }`,
    recommendedAction: "Fail-fast on application startup if JWT_SECRET is empty rather than defaulting to a predictable string.",
  },
  {
    id: "sec-103",
    title: "Permissive CORS origin wildcard with credentials allowed",
    severity: "Medium",
    category: "Configuration",
    repository: "campus-help-chatbot",
    file: "src/server.ts",
    line: 34,
    status: "Open",
    detectedAt: "1 day ago",
    description: "Access-Control-Allow-Origin is set to '*' while allow_credentials is set to true.",
    evidenceSnippet: `34  app.use(cors({ origin: "*", credentials: true }))`,
    recommendedAction: "Specify explicit allowed origin domain URLs in production environments.",
  },
];
