import { Repository, ActivityItem, PRItem, SecurityVulnerability } from "@/types/repository";

export const MOCK_REPOSITORIES: Repository[] = [
  {
    id: "ecommerce-platform",
    name: "ecommerce-platform",
    fullName: "acme-corp/ecommerce-platform",
    owner: "acme-corp",
    url: "https://github.com/acme-corp/ecommerce-platform",
    defaultBranch: "main",
    status: "active",
    syncStatus: "synced",
    lastSync: "18 seconds ago",
    fileCount: 1284,
    chunkCount: 24821,
    embeddingDimension: 1024,
    embeddingModel: "nvidia/nv-embedqa-e5-v5",
    language: "TypeScript",
    languageColor: "#3178c6",
    description: "Core Next.js & GraphQL store frontend, inventory orchestrator, and shopping cart service.",
  },
  {
    id: "payment-service",
    name: "payment-service",
    fullName: "acme-corp/payment-service",
    owner: "acme-corp",
    url: "https://github.com/acme-corp/payment-service",
    defaultBranch: "main",
    status: "active",
    syncStatus: "synced",
    lastSync: "4 mins ago",
    fileCount: 342,
    chunkCount: 8910,
    embeddingDimension: 1024,
    embeddingModel: "nvidia/nv-embedqa-e5-v5",
    language: "Python",
    languageColor: "#3572A5",
    description: "Stripe & PayPal gateway integration with asynchronous webhook handling and HMAC signature auditing.",
  },
  {
    id: "campus-help-chatbot",
    name: "campus-help-chatbot",
    fullName: "university-labs/campus-help-chatbot",
    owner: "university-labs",
    url: "https://github.com/university-labs/campus-help-chatbot",
    defaultBranch: "master",
    status: "active",
    syncStatus: "synced",
    lastSync: "12 mins ago",
    fileCount: 195,
    chunkCount: 4120,
    embeddingDimension: 1024,
    embeddingModel: "nvidia/nv-embedqa-e5-v5",
    language: "TypeScript",
    languageColor: "#3178c6",
    description: "Student portal virtual assistant with campus maps and course schedule FAQ RAG search.",
  },
  {
    id: "ai-support-copilot",
    name: "ai-support-copilot",
    fullName: "THARUN10-Coder/ai-support-copilot",
    owner: "THARUN10-Coder",
    url: "https://github.com/THARUN10-Coder/ai-support-copilot",
    defaultBranch: "main",
    status: "active",
    syncStatus: "synced",
    lastSync: "Just now",
    fileCount: 50,
    chunkCount: 136,
    embeddingDimension: 1024,
    embeddingModel: "nvidia/nv-embedqa-e5-v5",
    language: "Python",
    languageColor: "#3572A5",
    description: "Multi-channel AI support copilot indexing complete repository workflows and automated deployment pipelines.",
  },
  {
    id: "mobile-app",
    name: "mobile-app",
    fullName: "acme-corp/mobile-app",
    owner: "acme-corp",
    url: "https://github.com/acme-corp/mobile-app",
    defaultBranch: "main",
    status: "active",
    syncStatus: "warning",
    lastSync: "3 days ago",
    fileCount: 680,
    chunkCount: 14200,
    embeddingDimension: 1024,
    embeddingModel: "nvidia/nv-embedqa-e5-v5",
    language: "React Native",
    languageColor: "#61dafb",
    description: "Cross-platform iOS and Android mobile experience built on Expo and React Native.",
  },
  {
    id: "auth-gateway",
    name: "auth-gateway",
    fullName: "acme-corp/auth-gateway",
    owner: "acme-corp",
    url: "https://github.com/acme-corp/auth-gateway",
    defaultBranch: "main",
    status: "active",
    syncStatus: "synced",
    lastSync: "1 hour ago",
    fileCount: 220,
    chunkCount: 5410,
    embeddingDimension: 1024,
    embeddingModel: "nvidia/nv-embedqa-e5-v5",
    language: "Go",
    languageColor: "#00ADD8",
    description: "High-performance OAuth2, JWT, and SSO reverse-proxy with distributed Redis rate limiting.",
  },
];

export const MOCK_ACTIVITIES: ActivityItem[] = [
  {
    id: "act-1",
    type: "sync",
    title: "ecommerce-platform synchronized",
    repositoryId: "ecommerce-platform",
    repositoryName: "ecommerce-platform",
    timestamp: "18 seconds ago",
    details: "Processed 12 modified files via GitHub push webhook",
  },
  {
    id: "act-2",
    type: "push",
    title: "payment-service received a GitHub push",
    repositoryId: "payment-service",
    repositoryName: "payment-service",
    timestamp: "4 mins ago",
    details: "Commit 4f8a291 by @alex: Update Stripe API secret handling",
  },
  {
    id: "act-3",
    type: "query",
    title: "AI query completed across all repositories",
    repositoryId: "all",
    repositoryName: "All Repositories",
    timestamp: "8 mins ago",
    details: "Query: 'Which services depend on the payment API?' (1.4s)",
  },
  {
    id: "act-4",
    type: "graph",
    title: "Code graph updated",
    repositoryId: "campus-help-chatbot",
    repositoryName: "campus-help-chatbot",
    timestamp: "12 mins ago",
    details: "Re-indexed 14 component dependency edges",
  },
  {
    id: "act-5",
    type: "warning",
    title: "mobile-app requires re-indexing",
    repositoryId: "mobile-app",
    repositoryName: "mobile-app",
    timestamp: "1 hour ago",
    details: "Detected 48 unstaged branch modifications on origin/main",
  },
  {
    id: "act-6",
    type: "connect",
    title: "New repository connected: ai-support-copilot",
    repositoryId: "ai-support-copilot",
    repositoryName: "ai-support-copilot",
    timestamp: "2 hours ago",
    details: "Cloned and embedded 50 files into 136 vectors",
  },
];

export const MOCK_PRS: PRItem[] = [
  {
    id: "pr-42",
    number: 42,
    title: "Improve payment validation and HMAC verification",
    repositoryId: "payment-service",
    repositoryName: "payment-service",
    author: "sarah-dev",
    branch: "feat/hmac-verification",
    status: "open",
    aiRisk: "Medium",
    changedFiles: 6,
    additions: 148,
    deletions: 22,
    createdAt: "2 hours ago",
  },
  {
    id: "pr-118",
    number: 118,
    title: "Refactor cart checkout state and GraphQL mutations",
    repositoryId: "ecommerce-platform",
    repositoryName: "ecommerce-platform",
    author: "dev-dan",
    branch: "fix/cart-state",
    status: "open",
    aiRisk: "Low",
    changedFiles: 14,
    additions: 320,
    deletions: 180,
    createdAt: "5 hours ago",
  },
  {
    id: "pr-89",
    number: 89,
    title: "Upgrade NVIDIA NIM embed-qa to 1024D vectors",
    repositoryId: "ai-support-copilot",
    repositoryName: "ai-support-copilot",
    author: "tharun-coder",
    branch: "main",
    status: "merged",
    aiRisk: "Low",
    changedFiles: 4,
    additions: 85,
    deletions: 12,
    createdAt: "1 day ago",
  },
  {
    id: "pr-54",
    number: 54,
    title: "Update iOS Push notification entitlements for Expo 51",
    repositoryId: "mobile-app",
    repositoryName: "mobile-app",
    author: "mike-mobile",
    branch: "chore/expo-51",
    status: "open",
    aiRisk: "High",
    changedFiles: 28,
    additions: 540,
    deletions: 310,
    createdAt: "2 days ago",
  },
];

export const MOCK_SECURITY: SecurityVulnerability[] = [
  {
    id: "sec-1",
    title: "Unpinned dependency version in auth gateway",
    severity: "high",
    repositoryId: "auth-gateway",
    repositoryName: "auth-gateway",
    file: "go.mod:34",
    status: "open",
    detectedAt: "3 hours ago",
  },
  {
    id: "sec-2",
    title: "JWT secret fallback without strong entropy check",
    severity: "critical",
    repositoryId: "payment-service",
    repositoryName: "payment-service",
    file: "src/auth/token.py:42",
    status: "open",
    detectedAt: "1 day ago",
  },
  {
    id: "sec-3",
    title: "Outdated crypto-js package version in cart component",
    severity: "medium",
    repositoryId: "ecommerce-platform",
    repositoryName: "ecommerce-platform",
    file: "package.json:18",
    status: "open",
    detectedAt: "2 days ago",
  },
  {
    id: "sec-4",
    title: "Permissive CORS origin wildcard on local dev server",
    severity: "low",
    repositoryId: "campus-help-chatbot",
    repositoryName: "campus-help-chatbot",
    file: "backend/main.ts:28",
    status: "resolved",
    detectedAt: "4 days ago",
  },
];
